export const listOfRemoval = [
    'Buy Your Silence',
    'Depopulate',
    'Hold for Ransom',
    'Kill Shot',
    'Knockout Blow',
    'Disdainful Stroke',
    'Make Disappear',
    "An Offer You Can't Refuse",
    'Out of the Way',
    'Run Out of Town',
    'Rooftop Nuisance',
    'Sleep with the Fishes',
    'Witness Protection',
    'Deal Gone Bad',
    'Extract the Truth',
    'Grisly Sigil',
    'Incriminate',
    'Murder',
    'Whack',
    'Call In a Professional',
    "Light 'Em Up",
    'Ready to Rumble',
    'Strangle',
    'Structural Assault',
    'Torch Breath',
    "Bouncer's Beatdown",
    'Broken Wings',
    'Prizefight',
    'Cabaretti Charm',
    'Corpse Explosion',
    'Endless Detour',
    'Fatal Grudge',
    'Hostile Takeover',
    'Incandescent Aria',
    'Maestros Charm',
    'Obscura Charm',
    'Riveteers Charm',
    'Unleash the Inferno',
    'Void Rend',
];
